const UPDATE_ACTIVE_TODO_LIST_ID = "UPDATE_ACTIVE_TODO_LIST_ID";
const ADD_TODO_LIST = "ADD_TODO_LIST";
const UPDATE_TODO_LIST_LABEL = "UPDATE_TODO_LIST_LABEL";
const UPDATE_LISTS = "UPDATE_LISTS";
const DELETE_TODO_LIST = "DELETE_TODO_LIST";
const ADD_TASK = "ADD_TASK";
const DELETE_TASK = "DELETE_TASK";
const TOGGLE_PROPERTY_TASK = "TOGGLE_PROPERTY_TASK";
const UPDATING_EDITED_TASK = "UPDATING_EDITED_TASK";
const UPDATE_DATE_OR_TIME_TASK = "UPDATE_DATE_OR_TIME_TASK";
const ADD_SUB_TASK = "ADD_SUB_TASK";
const UPDATE_DATE_OR_TIME_SUB_TASK = "UPDATE_DATE_OR_TIME_SUB_TASK";
const WORK_WITH_SUB_TASK = "WORK_WITH_SUB_TASK";
const RESTORE_ITEM = "RESTORE_ITEM";
const DESTROY_ITEM = "DESTROY_ITEM";
const UPDATE_ITEM_IN_RECYCLE_BIN = "UPDATE_ITEM_IN_RECYCLE_BIN";
const AUTHENTICATION_USER = "AUTHENTICATION_USER";
const SIGN_OUT_ACCOUNT = "SIGN_OUT_ACCOUNT";
const SIGN_IN_ACCOUNT = "SIGN_IN_ACCOUNT";
const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
const TOGGLE_FILTER = "TOGGLE_FILTER";
const OFF_FILTER = "OFF_FILTER";

export {
    UPDATE_ACTIVE_TODO_LIST_ID,
    ADD_TODO_LIST,
    UPDATE_TODO_LIST_LABEL,
    UPDATE_LISTS,
    DELETE_TODO_LIST,
    ADD_TASK,
    DELETE_TASK,
    TOGGLE_PROPERTY_TASK,
    UPDATING_EDITED_TASK,
    UPDATE_DATE_OR_TIME_TASK,
    ADD_SUB_TASK,
    UPDATE_DATE_OR_TIME_SUB_TASK,
    WORK_WITH_SUB_TASK,
    RESTORE_ITEM,
    DESTROY_ITEM,
    UPDATE_ITEM_IN_RECYCLE_BIN,
    AUTHENTICATION_USER,
    SIGN_OUT_ACCOUNT,
    SIGN_IN_ACCOUNT,
    CLEAR_NOTIFICATION,
    TOGGLE_FILTER,
    OFF_FILTER
};